spring:
  application:
    name: spare-parts-service
  jpa:
      generate-ddl: false
      show-sql: true
      repositories:
        base-packages: com.sunlight.sapreParts.domain.po
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:                                          # 指定数据源
      url: jdbc:log4jdbc:mysql://mysql:3306/storage?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: net.sf.log4jdbc.DriverSpy

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registration:1111/eureka/

server:
  port: 8300